/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PrivateMail {
      
    export type MessageStruct = {sender: AddressLike, recipient: AddressLike, ciphertext: BytesLike, timestamp: BigNumberish, contentHash: BytesLike}

    export type MessageStructOutput = [sender: string, recipient: string, ciphertext: string, timestamp: bigint, contentHash: string] & {sender: string, recipient: string, ciphertext: string, timestamp: bigint, contentHash: string }
  
    }

  export interface PrivateMailInterface extends Interface {
    getFunction(nameOrSignature: "encryptionPublicKeys" | "getMessage" | "getPublicKey" | "hasRegisteredKey" | "isRegistered" | "messages" | "nextMessageId" | "registerPublicKey" | "sendMessage"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MessageSent" | "PublicKeyRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'encryptionPublicKeys', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMessage', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPublicKey', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRegisteredKey', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'messages', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextMessageId', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerPublicKey', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'sendMessage', values: [AddressLike, BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'encryptionPublicKeys', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRegisteredKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'messages', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextMessageId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerPublicKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendMessage', data: BytesLike): Result;
  }

  
    export namespace MessageSentEvent {
      export type InputTuple = [messageId: BigNumberish, sender: AddressLike, recipient: AddressLike, timestamp: BigNumberish, contentHash: BytesLike];
      export type OutputTuple = [messageId: bigint, sender: string, recipient: string, timestamp: bigint, contentHash: string];
      export interface OutputObject {messageId: bigint, sender: string, recipient: string, timestamp: bigint, contentHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PublicKeyRegisteredEvent {
      export type InputTuple = [owner: AddressLike, pubKey: BytesLike];
      export type OutputTuple = [owner: string, pubKey: string];
      export interface OutputObject {owner: string, pubKey: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PrivateMail extends BaseContract {
    
    connect(runner?: ContractRunner | null): PrivateMail;
    waitForDeployment(): Promise<this>;

    interface: PrivateMailInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    encryptionPublicKeys: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    getMessage: TypedContractMethod<
      [messageId: BigNumberish, ],
      [PrivateMail.MessageStructOutput],
      'view'
    >
    

    
    getPublicKey: TypedContractMethod<
      [owner: AddressLike, ],
      [string],
      'view'
    >
    

    
    hasRegisteredKey: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [owner: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    messages: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, string] & {sender: string, recipient: string, ciphertext: string, timestamp: bigint, contentHash: string }],
      'view'
    >
    

    
    nextMessageId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerPublicKey: TypedContractMethod<
      [pubKey: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    sendMessage: TypedContractMethod<
      [recipient: AddressLike, ciphertext: BytesLike, contentHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'encryptionPublicKeys'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMessage'): TypedContractMethod<
      [messageId: BigNumberish, ],
      [PrivateMail.MessageStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPublicKey'): TypedContractMethod<
      [owner: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'hasRegisteredKey'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [owner: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'messages'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, string, bigint, string] & {sender: string, recipient: string, ciphertext: string, timestamp: bigint, contentHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'nextMessageId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerPublicKey'): TypedContractMethod<
      [pubKey: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sendMessage'): TypedContractMethod<
      [recipient: AddressLike, ciphertext: BytesLike, contentHash: BytesLike, ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'MessageSent'): TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
getEvent(key: 'PublicKeyRegistered'): TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;

    filters: {
      
      'MessageSent(uint256,address,address,uint256,bytes32)': TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
      MessageSent: TypedContractEvent<MessageSentEvent.InputTuple, MessageSentEvent.OutputTuple, MessageSentEvent.OutputObject>;
    

      'PublicKeyRegistered(address,bytes)': TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;
      PublicKeyRegistered: TypedContractEvent<PublicKeyRegisteredEvent.InputTuple, PublicKeyRegisteredEvent.OutputTuple, PublicKeyRegisteredEvent.OutputObject>;
    
    };
  }